import type { Settings, T2WEvent } from "./types";

function mk(
  e: Partial<T2WEvent> & Pick<T2WEvent, "id" | "eventcode" | "name" | "start" | "ende">,
): T2WEvent {
  return {
    veranstalter: "—",
    ort: "—",
    status: "anfrage",
    verantwortlicher: "—",
    teilnehmer: 0,
    archiviert: false,
    notizen: "",
    outlookOrdner: null,
    sharepointOrdner: null,
    kontakte: [],
    aufgaben: [],
    dateien: [],
    kommunikation: [],
    ...e,
  };
}

export const DEMO_EVENTS: T2WEvent[] = [
  mk({
    id: "e1",
    eventcode: "260904_sommerfest_nordwerk",
    name: "Sommerfest Nordwerk 2026",
    veranstalter: "Nordwerk GmbH",
    ort: "Hamburg, Elbpark",
    start: "2026-09-04",
    ende: "2026-09-06",
    status: "zugesagt",
    verantwortlicher: "Lena Brandt",
    teilnehmer: 420,
    notizen: "Aufbau bereits am Vortag, Technikcheck Freitagmorgen.",
    outlookOrdner: "Auftraege26/Q3/260904_sommerfest_nordwerk",
    sharepointOrdner: "Events 2026/260904_sommerfest_nordwerk",
    kontakte: [
      {
        id: "k1",
        name: "Marion Kessler",
        rolle: "Auftraggeberin",
        email: "m.kessler@nordwerk.de",
        telefon: "+49 40 998812",
      },
      {
        id: "k2",
        name: "Tom Reiter",
        rolle: "Technik vor Ort",
        email: "t.reiter@nordwerk.de",
        telefon: "+49 151 2233445",
      },
    ],
    aufgaben: [
      {
        id: "a1",
        titel: "Bühnenplan final abstimmen",
        faellig: "2026-08-24",
        verantwortlich: "Lena Brandt",
        erledigt: false,
      },
      {
        id: "a2",
        titel: "Catering-Angebot einholen",
        faellig: "2026-08-20",
        verantwortlich: "Jonas Feld",
        erledigt: true,
      },
    ],
    dateien: [
      { id: "f1", name: "Angebot_Nordwerk.pdf", groesse: "412 KB", aktualisiert: "2026-08-02" },
      { id: "f2", name: "Hallenplan.dwg", groesse: "1,8 MB", aktualisiert: "2026-08-11" },
    ],
    kommunikation: [
      {
        id: "m1",
        kanal: "E-Mail",
        betreff: "Zusage Angebot",
        datum: "2026-08-05",
        autor: "Marion Kessler",
        text: "Wir nehmen das Angebot in der Variante B an.",
      },
      {
        id: "m2",
        kanal: "Notiz",
        betreff: "Technikbedarf",
        datum: "2026-08-12",
        autor: "Lena Brandt",
        text: "Zusätzlicher Stromverteiler notwendig.",
      },
    ],
  }),
  mk({
    id: "e2",
    eventcode: "260612_haendlertag_sued",
    name: "Händlertag Süd",
    veranstalter: "Auto Weiss AG",
    ort: "München, Messe Riem",
    start: "2026-06-12",
    ende: "2026-06-12",
    status: "zugesagt",
    verantwortlicher: "Jonas Feld",
    teilnehmer: 180,
    outlookOrdner: "Auftraege26/Q2/260612_haendlertag_sued",
    sharepointOrdner: "Events 2026/260612_haendlertag_sued",
    kontakte: [
      {
        id: "k3",
        name: "Sabine Roth",
        rolle: "Marketing",
        email: "roth@autoweiss.de",
        telefon: "+49 89 445566",
      },
    ],
    aufgaben: [
      {
        id: "a3",
        titel: "Nachbereitung & Rechnung",
        faellig: "2026-06-30",
        verantwortlich: "Jonas Feld",
        erledigt: true,
      },
    ],
    dateien: [
      {
        id: "f3",
        name: "Abrechnung_Haendlertag.xlsx",
        groesse: "96 KB",
        aktualisiert: "2026-06-28",
      },
    ],
    kommunikation: [
      {
        id: "m3",
        kanal: "E-Mail",
        betreff: "Feedback",
        datum: "2026-06-16",
        autor: "Sabine Roth",
        text: "Sehr gelungen, gerne wieder im Herbst.",
      },
    ],
  }),
  mk({
    id: "e3",
    eventcode: "260820_kickoff_werkstatt",
    name: "Kickoff Werkstatt Q3",
    veranstalter: "TIME2WIN intern",
    ort: "Berlin, Studio 4",
    start: "2026-08-20",
    ende: "2026-08-21",
    status: "anfrage",
    verantwortlicher: "Lena Brandt",
    teilnehmer: 45,
    notizen: "Raumverfügbarkeit noch offen.",
    outlookOrdner: "Auftraege26/Q3/260820_kickoff_werkstatt",
    kontakte: [],
    aufgaben: [
      {
        id: "a4",
        titel: "Raum bestätigen lassen",
        faellig: "2026-08-19",
        verantwortlich: "Lena Brandt",
        erledigt: false,
      },
    ],
    kommunikation: [
      {
        id: "m4",
        kanal: "Telefon",
        betreff: "Rückruf Location",
        datum: "2026-08-14",
        autor: "Lena Brandt",
        text: "Location meldet sich bis Montag.",
      },
    ],
  }),
  mk({
    id: "e4",
    eventcode: "261118_winterforum",
    name: "Winterforum 2026",
    veranstalter: "Stadtwerke Leipzig",
    ort: "Leipzig, Kongresshalle",
    start: "2026-11-18",
    ende: "2026-11-20",
    status: "zugesagt",
    verantwortlicher: "Mira Salm",
    teilnehmer: 700,
    outlookOrdner: "Auftraege26/Q4/261118_winterforum",
    sharepointOrdner: "Events 2026/261118_winterforum",
  }),
  mk({
    id: "e5",
    eventcode: "260930_produktlaunch_axo",
    name: "Produktlaunch AXO",
    veranstalter: "AXO Systems",
    ort: "Köln",
    start: "2026-09-30",
    ende: "2026-10-02",
    status: "anfrage",
    verantwortlicher: "Mira Salm",
    teilnehmer: 120,
    notizen: "Quartalsgrenze: Start Q3, Ende Q4.",
  }),
  mk({
    id: "e6",
    eventcode: "260403_fruehjahrsgala",
    name: "Frühjahrsgala",
    veranstalter: "Verein Hansa",
    ort: "Bremen",
    start: "2026-04-03",
    ende: "2026-04-04",
    status: "abgesagt",
    verantwortlicher: "Jonas Feld",
    archiviert: true,
    teilnehmer: 0,
    notizen: "Storniert wegen Terminkonflikt.",
  }),
  mk({
    id: "e7",
    eventcode: "260825_teamtag_nord",
    name: "Teamtag Nord",
    veranstalter: "Nordwerk GmbH",
    ort: "Kiel",
    start: "2026-08-25",
    ende: "2026-08-25",
    status: "zugesagt",
    verantwortlicher: "Lena Brandt",
    teilnehmer: 60,
  }),
  mk({
    id: "e8",
    eventcode: "260828_roadshow_west",
    name: "Roadshow West",
    veranstalter: "Auto Weiss AG",
    ort: "Düsseldorf",
    start: "2026-08-28",
    ende: "2026-08-31",
    status: "anfrage",
    verantwortlicher: "Mira Salm",
    teilnehmer: 240,
  }),
];

export const DEMO_SETTINGS: Settings = {
  outlookStammordner: "Auftraege26",
  jahresSites: [
    { jahr: "2025", url: "https://time2win.sharepoint.com/sites/Events2025" },
    { jahr: "2026", url: "https://time2win.sharepoint.com/sites/Events2026" },
  ],
};

export const VERANTWORTLICHE = ["Lena Brandt", "Jonas Feld", "Mira Salm"];
