DO $$ BEGIN CREATE TYPE "HardwareIssueType" AS ENUM ('PARTICIPANT', 'RENTAL', 'OTHER'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "HardwareStatus" AS ENUM ('OPEN', 'MAIL_SEND', 'NOTIFIED', 'RETURNED', 'COMPLETED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "ObjectNumberType" AS ENUM ('SINGLE', 'RANGE', 'NONE'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE TABLE IF NOT EXISTS "HardwareIssue" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(), "eventId" UUID NULL, "recipientName" TEXT NOT NULL,
  "issueType" "HardwareIssueType" NOT NULL, "objectName" TEXT NOT NULL, "objectNumberType" "ObjectNumberType" NOT NULL,
  "objectNumberSingle" TEXT, "objectNumberPrefix" TEXT, "objectNumberFrom" INTEGER, "objectNumberTo" INTEGER,
  "objectNumberPadding" INTEGER, "quantity" INTEGER NOT NULL, "status" "HardwareStatus" NOT NULL DEFAULT 'OPEN',
  "email" TEXT, "phone" TEXT, "issuedAt" TIMESTAMP(3), "dueDate" TIMESTAMP(3), "returnedAt" TIMESTAMP(3), "note" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "HardwareIssue_pkey" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "HardwareIssue_status_dueDate_idx" ON "HardwareIssue"("status", "dueDate");
INSERT INTO "HardwareIssue" ("eventId","recipientName","issueType","objectName","objectNumberType","objectNumberSingle","quantity","status","email","dueDate","updatedAt") VALUES
(NULL,'Jakob Klinglhuber','PARTICIPANT','T2W161 GPS Tracker','SINGLE','T2W161',1,'NOTIFIED','jakobklihu@gmail.com',CURRENT_DATE,CURRENT_TIMESTAMP),
(NULL,'Matthias Gruber','PARTICIPANT','T2W056 GPS TRACKER','SINGLE','T2W056',1,'NOTIFIED','m.p.gruber@a1.net',CURRENT_DATE,CURRENT_TIMESTAMP),
(NULL,'Manuel Gruber','PARTICIPANT','GPS-Tracker U4311','SINGLE','U4311',1,'NOTIFIED','katharina.gruber@sbg.at',CURRENT_DATE,CURRENT_TIMESTAMP),
(NULL,'Katharina Gruber','PARTICIPANT','GPS-Tracker U4310','SINGLE','U4310',1,'NOTIFIED','katharina.gruber@sbg.at',CURRENT_DATE,CURRENT_TIMESTAMP),
(NULL,'Michal Kubrycht','PARTICIPANT','GPS-Tracker U4460','SINGLE','U4460',1,'NOTIFIED','kubrycht.mich@gmail.com',CURRENT_DATE,CURRENT_TIMESTAMP),
(NULL,'Adam Hohl','PARTICIPANT','T2W548 ACTIVE TRANSPONDER','SINGLE','T2W548',1,'NOTIFIED','imadamhohl@gmail.com',CURRENT_DATE,CURRENT_TIMESTAMP),
(NULL,'Hubert Hartl','PARTICIPANT','LINDI1066 ACTIVE TRANSPONDER','SINGLE','LINDI1066',1,'NOTIFIED','hubert529@gmail.com',CURRENT_DATE,CURRENT_TIMESTAMP),
(NULL,'Martin Gugerbauer','PARTICIPANT','T2W969 ACTIVE TRANSPONDER','SINGLE','T2W969',1,'NOTIFIED','martl.gugerbauer@gmail.com',CURRENT_DATE,CURRENT_TIMESTAMP),
(NULL,'Manuel Abwerzger','PARTICIPANT','BRV510 ACTIVE TRANSPONDER','SINGLE','BRV510',1,'NOTIFIED','Manuel.abwerzger@icloud.com',CURRENT_DATE,CURRENT_TIMESTAMP),
(NULL,'Peter Huber','PARTICIPANT','BRV515 ACTIVE TRANSPONDER','SINGLE','BRV515',1,'NOTIFIED','peter_huber@gmx.at',CURRENT_DATE,CURRENT_TIMESTAMP),
(NULL,'Timo Zeiner','PARTICIPANT','BRV498 ACTIVE TRANSPONDER','SINGLE','BRV498',1,'NOTIFIED','timo.zeiner@gmail.com',CURRENT_DATE,CURRENT_TIMESTAMP),
(NULL,'Juan camilo Ortiz perez','PARTICIPANT','LINDI1080 ACTIVE TRANSPONDER','SINGLE','LINDI1080',1,'NOTIFIED','milojahrezpecirco@gmail.com',CURRENT_DATE,CURRENT_TIMESTAMP),
(NULL,'Ruth Weinert','PARTICIPANT','LINDI1005 ACTIVE TRANSPONDER','SINGLE','LINDI1005',1,'NOTIFIED','ruth.ch@web.de',CURRENT_DATE,CURRENT_TIMESTAMP),
(NULL,'Alexander Heinzelmann','PARTICIPANT','T2W19 ACTIVE TRANSPONDER','SINGLE','T2W19',1,'NOTIFIED','alex.heinzelmann@gmx.net',CURRENT_DATE,CURRENT_TIMESTAMP),
(NULL,'Verena Sigl','PARTICIPANT','BRV497 ACTIVE TRANSPONDER','SINGLE','BRV497',1,'NOTIFIED','siglverena.1@gmx.at',CURRENT_DATE,CURRENT_TIMESTAMP),
(NULL,'Anika Noggler','PARTICIPANT','BRV352 ACTIVE TRANSPONDER','SINGLE','BRV352',1,'NOTIFIED','anika.noggler@gmail.com',CURRENT_DATE,CURRENT_TIMESTAMP),
(NULL,'Vadym Pypko','PARTICIPANT','T2W293 ACTIVE TRANSPONDER','SINGLE','T2W293',1,'NOTIFIED','vpipko1@gmail.com',CURRENT_DATE,CURRENT_TIMESTAMP),
(NULL,'Paula Creamer','PARTICIPANT','T2W83 ACTIVE TRANSPONDER','SINGLE','T2W83',1,'NOTIFIED','info@paula-bewegt.de',CURRENT_DATE,CURRENT_TIMESTAMP);
