ALTER TABLE "Sport" ADD COLUMN "sortOrder" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ServiceOption" ADD COLUMN "sortOrder" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "HardwareObjectOption" ADD COLUMN "sortOrder" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "EventRoleOption" ADD COLUMN "sortOrder" INTEGER NOT NULL DEFAULT 0;
