/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AngeboteRouteImport } from './routes/angebote'
import { Route as AufgabenRouteImport } from './routes/aufgaben'
import { Route as EinstellungenRouteImport } from './routes/einstellungen'
import { Route as KalenderRouteImport } from './routes/kalender'
import { Route as KontakteRouteImport } from './routes/kontakte'
import { Route as RechnungenRouteImport } from './routes/rechnungen'
import { Route as StyleguideRouteImport } from './routes/styleguide'
import { Route as VeranstaltungenRouteImport } from './routes/veranstaltungen'
import { Route as EventsEventcodeRouteImport } from './routes/events.$eventcode'
import { Route as VariantenIndexRouteImport } from './routes/varianten.index'
import { Route as VariantenOpsRouteImport } from './routes/varianten.ops'
import { Route as VariantenTimelineRouteImport } from './routes/varianten.timeline'
import { Route as VariantenWorkspaceRouteImport } from './routes/varianten.workspace'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AngeboteRoute = AngeboteRouteImport.update({
  id: '/angebote',
  path: '/angebote',
  getParentRoute: () => rootRouteImport,
} as any)
const AufgabenRoute = AufgabenRouteImport.update({
  id: '/aufgaben',
  path: '/aufgaben',
  getParentRoute: () => rootRouteImport,
} as any)
const EinstellungenRoute = EinstellungenRouteImport.update({
  id: '/einstellungen',
  path: '/einstellungen',
  getParentRoute: () => rootRouteImport,
} as any)
const KalenderRoute = KalenderRouteImport.update({
  id: '/kalender',
  path: '/kalender',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakteRoute = KontakteRouteImport.update({
  id: '/kontakte',
  path: '/kontakte',
  getParentRoute: () => rootRouteImport,
} as any)
const RechnungenRoute = RechnungenRouteImport.update({
  id: '/rechnungen',
  path: '/rechnungen',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleguideRoute = StyleguideRouteImport.update({
  id: '/styleguide',
  path: '/styleguide',
  getParentRoute: () => rootRouteImport,
} as any)
const VeranstaltungenRoute = VeranstaltungenRouteImport.update({
  id: '/veranstaltungen',
  path: '/veranstaltungen',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventcodeRoute = EventsEventcodeRouteImport.update({
  id: '/events/$eventcode',
  path: '/events/$eventcode',
  getParentRoute: () => rootRouteImport,
} as any)
const VariantenIndexRoute = VariantenIndexRouteImport.update({
  id: '/varianten/',
  path: '/varianten/',
  getParentRoute: () => rootRouteImport,
} as any)
const VariantenOpsRoute = VariantenOpsRouteImport.update({
  id: '/varianten/ops',
  path: '/varianten/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const VariantenTimelineRoute = VariantenTimelineRouteImport.update({
  id: '/varianten/timeline',
  path: '/varianten/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const VariantenWorkspaceRoute = VariantenWorkspaceRouteImport.update({
  id: '/varianten/workspace',
  path: '/varianten/workspace',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/angebote': typeof AngeboteRoute
  '/aufgaben': typeof AufgabenRoute
  '/einstellungen': typeof EinstellungenRoute
  '/kalender': typeof KalenderRoute
  '/kontakte': typeof KontakteRoute
  '/rechnungen': typeof RechnungenRoute
  '/styleguide': typeof StyleguideRoute
  '/veranstaltungen': typeof VeranstaltungenRoute
  '/events/$eventcode': typeof EventsEventcodeRoute
  '/varianten/ops': typeof VariantenOpsRoute
  '/varianten/timeline': typeof VariantenTimelineRoute
  '/varianten/workspace': typeof VariantenWorkspaceRoute
  '/varianten/': typeof VariantenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/angebote': typeof AngeboteRoute
  '/aufgaben': typeof AufgabenRoute
  '/einstellungen': typeof EinstellungenRoute
  '/kalender': typeof KalenderRoute
  '/kontakte': typeof KontakteRoute
  '/rechnungen': typeof RechnungenRoute
  '/styleguide': typeof StyleguideRoute
  '/veranstaltungen': typeof VeranstaltungenRoute
  '/events/$eventcode': typeof EventsEventcodeRoute
  '/varianten/ops': typeof VariantenOpsRoute
  '/varianten/timeline': typeof VariantenTimelineRoute
  '/varianten/workspace': typeof VariantenWorkspaceRoute
  '/varianten': typeof VariantenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/angebote': typeof AngeboteRoute
  '/aufgaben': typeof AufgabenRoute
  '/einstellungen': typeof EinstellungenRoute
  '/kalender': typeof KalenderRoute
  '/kontakte': typeof KontakteRoute
  '/rechnungen': typeof RechnungenRoute
  '/styleguide': typeof StyleguideRoute
  '/veranstaltungen': typeof VeranstaltungenRoute
  '/events/$eventcode': typeof EventsEventcodeRoute
  '/varianten/ops': typeof VariantenOpsRoute
  '/varianten/timeline': typeof VariantenTimelineRoute
  '/varianten/workspace': typeof VariantenWorkspaceRoute
  '/varianten/': typeof VariantenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/angebote'
    | '/aufgaben'
    | '/einstellungen'
    | '/kalender'
    | '/kontakte'
    | '/rechnungen'
    | '/styleguide'
    | '/veranstaltungen'
    | '/events/$eventcode'
    | '/varianten/ops'
    | '/varianten/timeline'
    | '/varianten/workspace'
    | '/varianten/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/angebote'
    | '/aufgaben'
    | '/einstellungen'
    | '/kalender'
    | '/kontakte'
    | '/rechnungen'
    | '/styleguide'
    | '/veranstaltungen'
    | '/events/$eventcode'
    | '/varianten/ops'
    | '/varianten/timeline'
    | '/varianten/workspace'
    | '/varianten'
  id:
    | '__root__'
    | '/'
    | '/angebote'
    | '/aufgaben'
    | '/einstellungen'
    | '/kalender'
    | '/kontakte'
    | '/rechnungen'
    | '/styleguide'
    | '/veranstaltungen'
    | '/events/$eventcode'
    | '/varianten/ops'
    | '/varianten/timeline'
    | '/varianten/workspace'
    | '/varianten/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AngeboteRoute: typeof AngeboteRoute
  AufgabenRoute: typeof AufgabenRoute
  EinstellungenRoute: typeof EinstellungenRoute
  KalenderRoute: typeof KalenderRoute
  KontakteRoute: typeof KontakteRoute
  RechnungenRoute: typeof RechnungenRoute
  StyleguideRoute: typeof StyleguideRoute
  VeranstaltungenRoute: typeof VeranstaltungenRoute
  EventsEventcodeRoute: typeof EventsEventcodeRoute
  VariantenOpsRoute: typeof VariantenOpsRoute
  VariantenTimelineRoute: typeof VariantenTimelineRoute
  VariantenWorkspaceRoute: typeof VariantenWorkspaceRoute
  VariantenIndexRoute: typeof VariantenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/angebote': {
      id: '/angebote'
      path: '/angebote'
      fullPath: '/angebote'
      preLoaderRoute: typeof AngeboteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aufgaben': {
      id: '/aufgaben'
      path: '/aufgaben'
      fullPath: '/aufgaben'
      preLoaderRoute: typeof AufgabenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einstellungen': {
      id: '/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof EinstellungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalender': {
      id: '/kalender'
      path: '/kalender'
      fullPath: '/kalender'
      preLoaderRoute: typeof KalenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakte': {
      id: '/kontakte'
      path: '/kontakte'
      fullPath: '/kontakte'
      preLoaderRoute: typeof KontakteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rechnungen': {
      id: '/rechnungen'
      path: '/rechnungen'
      fullPath: '/rechnungen'
      preLoaderRoute: typeof RechnungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styleguide': {
      id: '/styleguide'
      path: '/styleguide'
      fullPath: '/styleguide'
      preLoaderRoute: typeof StyleguideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veranstaltungen': {
      id: '/veranstaltungen'
      path: '/veranstaltungen'
      fullPath: '/veranstaltungen'
      preLoaderRoute: typeof VeranstaltungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventcode': {
      id: '/events/$eventcode'
      path: '/events/$eventcode'
      fullPath: '/events/$eventcode'
      preLoaderRoute: typeof EventsEventcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/varianten/': {
      id: '/varianten/'
      path: '/varianten'
      fullPath: '/varianten/'
      preLoaderRoute: typeof VariantenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/varianten/ops': {
      id: '/varianten/ops'
      path: '/varianten/ops'
      fullPath: '/varianten/ops'
      preLoaderRoute: typeof VariantenOpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/varianten/timeline': {
      id: '/varianten/timeline'
      path: '/varianten/timeline'
      fullPath: '/varianten/timeline'
      preLoaderRoute: typeof VariantenTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/varianten/workspace': {
      id: '/varianten/workspace'
      path: '/varianten/workspace'
      fullPath: '/varianten/workspace'
      preLoaderRoute: typeof VariantenWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AngeboteRoute: AngeboteRoute,
  AufgabenRoute: AufgabenRoute,
  EinstellungenRoute: EinstellungenRoute,
  KalenderRoute: KalenderRoute,
  KontakteRoute: KontakteRoute,
  RechnungenRoute: RechnungenRoute,
  StyleguideRoute: StyleguideRoute,
  VeranstaltungenRoute: VeranstaltungenRoute,
  EventsEventcodeRoute: EventsEventcodeRoute,
  VariantenOpsRoute: VariantenOpsRoute,
  VariantenTimelineRoute: VariantenTimelineRoute,
  VariantenWorkspaceRoute: VariantenWorkspaceRoute,
  VariantenIndexRoute: VariantenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}

